package city_commute;



import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author SUHANEE PATEL
 */
public class busSeat extends javax.swing.JFrame {

    String x;
    ArrayList x1 = new ArrayList();
    String y = "AH01";

    int count;

    /**
     * Creates new form busSeat
     */
    public busSeat() {
        initComponents();
         this.setSize(1020, 750);
        JLabel[] a = {X1Y1, X1Y2, X1Y3, X1Y4, X1Y5, X1Y6, X1Y7, X2Y1, X2Y2, X2Y3, X2Y4, X2Y5, X2Y6, X2Y7, X3Y1, X3Y2, X3Y3, X3Y4, X3Y5, X3Y6, X3Y7, X4Y1, X4Y2, X4Y3, X4Y4, X4Y5, X4Y6, X4Y7};
        System.out.println(a[19].getText());
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/oopproject", "root", "");
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT seat FROM seat WHERE " + y + "= 1");
            while (rs.next()) {
                //System.out.println(rs.getString("seat"));
                for (int i = 0; i < 28; i++) {
                    if (a[i].getText().equals(rs.getString("seat"))) {
                        a[i] .setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
                    }
                }
            }

            conn.close();
            rs.close();
            stmt.close();
        } catch (Exception e) {
            System.out.println(e);
        }
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/oopproject", "root", "");
            Statement stmt1 = con.createStatement();
            ResultSet rs1 = stmt1.executeQuery("SELECT COUNT(*) FROM seat WHERE " + y + "=1");
            while (rs1.next()) {
                count = rs1.getInt("COUNT(*)");
            }
            System.out.println(count);
            String counts = String.valueOf(count);
            jLabel19.setText(counts);
            int c = 28 - count;
            System.out.println(c);
            String counts1 = String.valueOf(c);
            jLabel25.setText(counts1);

            con.close();
            rs1.close();
            stmt1.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/oopproject", "root", "");
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT distance FROM profile2 ");
            while (rs.next()) {
                String fare = rs.getString("distance");
                double cost = Math.round(Double.parseDouble(fare) * 3);
                jLabel17.setText(Double.toString(cost));
            }

            conn.close();
            rs.close();
            stmt.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        Connection con = null;
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/oopproject", "root", "");
            Statement stmt = conn.createStatement();

            ResultSet rs2 = stmt.executeQuery("select `cust` from visit;");
            while (rs2.next()) {
                String cust = rs2.getString("cust");
                jLabel1.setText(cust);
            }

            stmt.close();
            con.close();
        } catch (Exception e) {
            //System.out.println("connection was not established ");
        }

    }

    public String getbus() {
        return y;
    }

    public ArrayList getseat() {
        return x1;
    }

    public String fare() {
        return jLabel17.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        X1Y1 = new javax.swing.JLabel();
        X1Y2 = new javax.swing.JLabel();
        X1Y4 = new javax.swing.JLabel();
        X2Y1 = new javax.swing.JLabel();
        X2Y2 = new javax.swing.JLabel();
        X2Y3 = new javax.swing.JLabel();
        X1Y5 = new javax.swing.JLabel();
        X1Y6 = new javax.swing.JLabel();
        X1Y7 = new javax.swing.JLabel();
        X2Y5 = new javax.swing.JLabel();
        X2Y6 = new javax.swing.JLabel();
        X2Y7 = new javax.swing.JLabel();
        X3Y1 = new javax.swing.JLabel();
        X3Y2 = new javax.swing.JLabel();
        X3Y4 = new javax.swing.JLabel();
        X3Y5 = new javax.swing.JLabel();
        X3Y6 = new javax.swing.JLabel();
        X3Y7 = new javax.swing.JLabel();
        X4Y1 = new javax.swing.JLabel();
        X4Y2 = new javax.swing.JLabel();
        X4Y3 = new javax.swing.JLabel();
        X4Y4 = new javax.swing.JLabel();
        X4Y5 = new javax.swing.JLabel();
        X4Y6 = new javax.swing.JLabel();
        X4Y7 = new javax.swing.JLabel();
        X3Y3 = new javax.swing.JLabel();
        X2Y4 = new javax.swing.JLabel();
        X1Y3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        yes = new javax.swing.JLabel();
        no = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1010, 730));

        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1010, 700));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Click on the available seat to book it ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 50, 370, 28);

        X1Y1.setBackground(new java.awt.Color(255, 153, 153));
        X1Y1.setForeground(new java.awt.Color(255, 255, 255));
        X1Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X1Y1.setText("X1Y1");
        X1Y1.setToolTipText("");
        X1Y1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X1Y1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X1Y1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X1Y1MouseExited(evt);
            }
        });
        jPanel1.add(X1Y1);
        X1Y1.setBounds(140, 120, 60, 50);

        X1Y2.setBackground(new java.awt.Color(255, 153, 153));
        X1Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X1Y2.setText("X1Y2");
        X1Y2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X1Y2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X1Y2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X1Y2MouseExited(evt);
            }
        });
        jPanel1.add(X1Y2);
        X1Y2.setBounds(240, 120, 60, 50);

        X1Y4.setBackground(new java.awt.Color(255, 153, 153));
        X1Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X1Y4.setText("X1Y4");
        X1Y4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X1Y4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X1Y4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X1Y4MouseExited(evt);
            }
        });
        jPanel1.add(X1Y4);
        X1Y4.setBounds(440, 120, 60, 50);

        X2Y1.setBackground(new java.awt.Color(255, 153, 153));
        X2Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X2Y1.setText("X2Y1");
        X2Y1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X2Y1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X2Y1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X2Y1MouseExited(evt);
            }
        });
        jPanel1.add(X2Y1);
        X2Y1.setBounds(140, 190, 60, 50);

        X2Y2.setBackground(new java.awt.Color(255, 153, 153));
        X2Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X2Y2.setText("X2Y2");
        X2Y2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X2Y2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X2Y2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X2Y2MouseExited(evt);
            }
        });
        jPanel1.add(X2Y2);
        X2Y2.setBounds(240, 190, 60, 50);

        X2Y3.setBackground(new java.awt.Color(255, 153, 153));
        X2Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X2Y3.setText("X2Y3");
        X2Y3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X2Y3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X2Y3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X2Y3MouseExited(evt);
            }
        });
        jPanel1.add(X2Y3);
        X2Y3.setBounds(340, 190, 60, 50);

        X1Y5.setBackground(new java.awt.Color(255, 153, 153));
        X1Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X1Y5.setText("X1Y5");
        X1Y5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X1Y5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X1Y5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X1Y5MouseExited(evt);
            }
        });
        jPanel1.add(X1Y5);
        X1Y5.setBounds(540, 120, 60, 50);

        X1Y6.setBackground(new java.awt.Color(255, 153, 153));
        X1Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X1Y6.setText("X1Y6");
        X1Y6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X1Y6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X1Y6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X1Y6MouseExited(evt);
            }
        });
        jPanel1.add(X1Y6);
        X1Y6.setBounds(640, 120, 60, 50);

        X1Y7.setBackground(new java.awt.Color(255, 153, 153));
        X1Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X1Y7.setText("X1Y7");
        X1Y7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X1Y7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X1Y7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X1Y7MouseExited(evt);
            }
        });
        jPanel1.add(X1Y7);
        X1Y7.setBounds(740, 120, 60, 50);

        X2Y5.setBackground(new java.awt.Color(255, 153, 153));
        X2Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X2Y5.setText("X2Y5");
        X2Y5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X2Y5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X2Y5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X2Y5MouseExited(evt);
            }
        });
        jPanel1.add(X2Y5);
        X2Y5.setBounds(540, 190, 60, 50);

        X2Y6.setBackground(new java.awt.Color(255, 153, 153));
        X2Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X2Y6.setText("X2Y6");
        X2Y6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X2Y6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X2Y6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X2Y6MouseExited(evt);
            }
        });
        jPanel1.add(X2Y6);
        X2Y6.setBounds(640, 190, 60, 50);

        X2Y7.setBackground(new java.awt.Color(255, 153, 153));
        X2Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X2Y7.setText("X2Y7");
        X2Y7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X2Y7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X2Y7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X2Y7MouseExited(evt);
            }
        });
        jPanel1.add(X2Y7);
        X2Y7.setBounds(740, 190, 60, 50);

        X3Y1.setBackground(new java.awt.Color(255, 153, 153));
        X3Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X3Y1.setText("X3Y1");
        X3Y1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X3Y1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X3Y1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X3Y1MouseExited(evt);
            }
        });
        jPanel1.add(X3Y1);
        X3Y1.setBounds(140, 350, 60, 50);

        X3Y2.setBackground(new java.awt.Color(255, 153, 153));
        X3Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X3Y2.setText("X3Y2");
        X3Y2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X3Y2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X3Y2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X3Y2MouseExited(evt);
            }
        });
        jPanel1.add(X3Y2);
        X3Y2.setBounds(240, 350, 60, 50);

        X3Y4.setBackground(new java.awt.Color(255, 153, 153));
        X3Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X3Y4.setText("X3Y4");
        X3Y4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X3Y4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X3Y4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X3Y4MouseExited(evt);
            }
        });
        jPanel1.add(X3Y4);
        X3Y4.setBounds(440, 350, 60, 50);

        X3Y5.setBackground(new java.awt.Color(255, 153, 153));
        X3Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X3Y5.setText("X3Y5");
        X3Y5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X3Y5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X3Y5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X3Y5MouseExited(evt);
            }
        });
        jPanel1.add(X3Y5);
        X3Y5.setBounds(540, 350, 60, 50);

        X3Y6.setBackground(new java.awt.Color(255, 153, 153));
        X3Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X3Y6.setText("X3Y6");
        X3Y6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X3Y6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X3Y6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X3Y6MouseExited(evt);
            }
        });
        jPanel1.add(X3Y6);
        X3Y6.setBounds(640, 350, 60, 50);

        X3Y7.setBackground(new java.awt.Color(255, 153, 153));
        X3Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X3Y7.setText("X3Y7");
        X3Y7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X3Y7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X3Y7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X3Y7MouseExited(evt);
            }
        });
        jPanel1.add(X3Y7);
        X3Y7.setBounds(740, 350, 60, 50);

        X4Y1.setBackground(new java.awt.Color(255, 153, 153));
        X4Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X4Y1.setText("X4Y1");
        X4Y1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X4Y1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X4Y1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X4Y1MouseExited(evt);
            }
        });
        jPanel1.add(X4Y1);
        X4Y1.setBounds(140, 420, 60, 50);

        X4Y2.setBackground(new java.awt.Color(255, 153, 153));
        X4Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X4Y2.setText("X4Y2");
        X4Y2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X4Y2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X4Y2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X4Y2MouseExited(evt);
            }
        });
        jPanel1.add(X4Y2);
        X4Y2.setBounds(240, 420, 60, 50);

        X4Y3.setBackground(new java.awt.Color(255, 153, 153));
        X4Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X4Y3.setText("X4Y3");
        X4Y3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X4Y3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X4Y3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X4Y3MouseExited(evt);
            }
        });
        jPanel1.add(X4Y3);
        X4Y3.setBounds(340, 420, 60, 50);

        X4Y4.setBackground(new java.awt.Color(255, 153, 153));
        X4Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X4Y4.setText("X4Y4");
        X4Y4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X4Y4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X4Y4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X4Y4MouseExited(evt);
            }
        });
        jPanel1.add(X4Y4);
        X4Y4.setBounds(440, 420, 60, 50);

        X4Y5.setBackground(new java.awt.Color(255, 153, 153));
        X4Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X4Y5.setText("X4Y5");
        X4Y5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X4Y5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X4Y5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X4Y5MouseExited(evt);
            }
        });
        jPanel1.add(X4Y5);
        X4Y5.setBounds(540, 420, 60, 50);

        X4Y6.setBackground(new java.awt.Color(255, 153, 153));
        X4Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X4Y6.setText("X4Y6");
        X4Y6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X4Y6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X4Y6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X4Y6MouseExited(evt);
            }
        });
        jPanel1.add(X4Y6);
        X4Y6.setBounds(640, 420, 60, 50);

        X4Y7.setBackground(new java.awt.Color(255, 153, 153));
        X4Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X4Y7.setText("X4Y7");
        X4Y7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X4Y7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X4Y7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X4Y7MouseExited(evt);
            }
        });
        jPanel1.add(X4Y7);
        X4Y7.setBounds(740, 420, 60, 50);

        X3Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X3Y3.setText("X3Y3");
        X3Y3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X3Y3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X3Y3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X3Y3MouseExited(evt);
            }
        });
        jPanel1.add(X3Y3);
        X3Y3.setBounds(340, 350, 60, 50);

        X2Y4.setBackground(new java.awt.Color(255, 153, 153));
        X2Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X2Y4.setText("X2Y4");
        X2Y4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X2Y4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X2Y4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X2Y4MouseExited(evt);
            }
        });
        jPanel1.add(X2Y4);
        X2Y4.setBounds(440, 190, 60, 50);

        X1Y3.setBackground(new java.awt.Color(255, 153, 153));
        X1Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p.jpg"))); // NOI18N
        X1Y3.setText("X1Y3");
        X1Y3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X1Y3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X1Y3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X1Y3MouseExited(evt);
            }
        });
        jPanel1.add(X1Y3);
        X1Y3.setBounds(340, 120, 60, 50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 204));
        jLabel4.setText("SEAT STATUS");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 520, 270, 60);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 204));
        jLabel6.setText("BUS ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(850, 100, 100, 80);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 204));
        jLabel9.setText("SEAT ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(850, 240, 130, 70);

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("AH01");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(850, 180, 100, 40);

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(jLabel13);
        jLabel13.setBounds(830, 320, 150, 40);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 153, 204));
        jLabel15.setText("FARE");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(850, 400, 140, 40);

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel17);
        jLabel17.setBounds(820, 450, 170, 50);

        jLabel21.setFont(new java.awt.Font("Segoe Script", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 153, 204));
        jLabel21.setText("booked");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(420, 540, 77, 33);

        jLabel23.setFont(new java.awt.Font("Segoe Script", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 153, 204));
        jLabel23.setText("available");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(640, 540, 103, 33);

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel19);
        jLabel19.setBounds(530, 530, 60, 40);

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 30)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel25);
        jLabel25.setBounds(770, 530, 70, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 204));
        jLabel3.setText("CONFIRM ?");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 624, 205, 42);

        yes.setFont(new java.awt.Font("Segoe Script", 1, 35)); // NOI18N
        yes.setForeground(new java.awt.Color(255, 255, 255));
        yes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yes.setText("yes");
        yes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yesMouseClicked(evt);
            }
        });
        jPanel1.add(yes);
        yes.setBounds(290, 620, 86, 57);

        no.setFont(new java.awt.Font("Segoe Script", 1, 35)); // NOI18N
        no.setForeground(new java.awt.Color(255, 255, 255));
        no.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no.setText("no");
        no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noMouseClicked(evt);
            }
        });
        jPanel1.add(no);
        no.setBounds(410, 620, 86, 57);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 153, 204));
        jLabel30.setText("PROCEED");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel30);
        jLabel30.setBounds(750, 620, 177, 42);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bus1.png"))); // NOI18N
        jPanel1.add(jLabel32);
        jLabel32.setBounds(0, 90, 810, 421);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(930, 10, 0, 0);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/suhu11.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(930, 0, 50, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/suhu10.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(870, 0, 50, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/capture2.JPG"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 1000, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    private void X1Y1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y1MouseEntered
        // TODO add your handling code here:
        X1Y1.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X1Y1");
    }//GEN-LAST:event_X1Y1MouseEntered

    private void X1Y1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y1MouseExited
        // TODO add your handling code here:
        X1Y1.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X1Y1MouseExited

    private void X1Y2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y2MouseEntered
        // TODO add your handling code here:
        X1Y2.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X1Y2");
    }//GEN-LAST:event_X1Y2MouseEntered

    private void X1Y3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y3MouseEntered
        // TODO add your handling code here:
        X1Y3.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X1Y3");
    }//GEN-LAST:event_X1Y3MouseEntered

    private void X1Y4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y4MouseEntered
        // TODO add your handling code here:
        X1Y4.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X1Y4");
    }//GEN-LAST:event_X1Y4MouseEntered

    private void X1Y5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y5MouseEntered
        // TODO add your handling code here:
        X1Y5.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X1Y5");
    }//GEN-LAST:event_X1Y5MouseEntered

    private void X1Y6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y6MouseEntered
        // TODO add your handling code here:
        X1Y6.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X1Y6");
    }//GEN-LAST:event_X1Y6MouseEntered

    private void X1Y7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y7MouseEntered
        // TODO add your handling code here:
        X1Y7.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X1Y7");
    }//GEN-LAST:event_X1Y7MouseEntered

    private void X2Y7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y7MouseEntered
        // TODO add your handling code here:
        X2Y7.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X2Y7");
    }//GEN-LAST:event_X2Y7MouseEntered

    private void X2Y6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y6MouseEntered
        // TODO add your handling code here:
        X2Y6.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X2Y6");
    }//GEN-LAST:event_X2Y6MouseEntered

    private void X2Y5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y5MouseEntered
        // TODO add your handling code here:
        X2Y5.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X2Y5");
    }//GEN-LAST:event_X2Y5MouseEntered

    private void X2Y4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y4MouseEntered
        // TODO add your handling code here:
        X2Y4.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X2Y4");
    }//GEN-LAST:event_X2Y4MouseEntered

    private void X2Y3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y3MouseEntered
        // TODO add your handling code here:
        X2Y3.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X2Y3");
    }//GEN-LAST:event_X2Y3MouseEntered

    private void X2Y2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y2MouseEntered
        // TODO add your handling code here:
        X2Y2.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X2Y2");
    }//GEN-LAST:event_X2Y2MouseEntered

    private void X2Y1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y1MouseEntered
        // TODO add your handling code here:
        X2Y1.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X2Y1");
    }//GEN-LAST:event_X2Y1MouseEntered

    private void X3Y1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y1MouseEntered
        // TODO add your handling code here:
        X3Y1.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X3Y1");
    }//GEN-LAST:event_X3Y1MouseEntered

    private void X3Y2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y2MouseEntered
        // TODO add your handling code here:
        X3Y2.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X3Y2");
    }//GEN-LAST:event_X3Y2MouseEntered

    private void X3Y3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y3MouseEntered
        // TODO add your handling code here:
        X3Y3.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X3Y3");
    }//GEN-LAST:event_X3Y3MouseEntered

    private void X3Y4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y4MouseEntered
        // TODO add your handling code here:
        X3Y4.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X3Y4");
    }//GEN-LAST:event_X3Y4MouseEntered

    private void X3Y5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y5MouseEntered
        // TODO add your handling code here:
        X3Y5.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X3Y5");
    }//GEN-LAST:event_X3Y5MouseEntered

    private void X3Y6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y6MouseEntered
        // TODO add your handling code here:
        X3Y6.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X3Y6");
    }//GEN-LAST:event_X3Y6MouseEntered

    private void X3Y7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y7MouseEntered
        // TODO add your handling code here:
        X3Y7.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X3Y7");
    }//GEN-LAST:event_X3Y7MouseEntered

    private void X4Y7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y7MouseEntered
        // TODO add your handling code here:
        X4Y7.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X4Y7");
    }//GEN-LAST:event_X4Y7MouseEntered

    private void X4Y6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y6MouseEntered
        // TODO add your handling code here:
        X4Y6.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X4Y6");
    }//GEN-LAST:event_X4Y6MouseEntered

    private void X4Y5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y5MouseEntered
        // TODO add your handling code here:
        X4Y5.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X4Y5");
    }//GEN-LAST:event_X4Y5MouseEntered

    private void X4Y4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y4MouseEntered
        // TODO add your handling code here:
        X4Y4.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X4Y4");
    }//GEN-LAST:event_X4Y4MouseEntered

    private void X4Y3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y3MouseEntered
        // TODO add your handling code here:
        X4Y3.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X4Y3");
    }//GEN-LAST:event_X4Y3MouseEntered

    private void X4Y2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y2MouseEntered
        // TODO add your handling code here:
        X4Y2.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X4Y2");
    }//GEN-LAST:event_X4Y2MouseEntered

    private void X4Y1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y1MouseEntered
        // TODO add your handling code here:
        X4Y1.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 102, 204)));
        jLabel13.setText("X4Y1");
    }//GEN-LAST:event_X4Y1MouseEntered

    private void X1Y2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y2MouseExited
        // TODO add your handling code here:
        X1Y2.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X1Y2MouseExited

    private void X1Y3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y3MouseExited
        // TODO add your handling code here:
        X1Y3.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X1Y3MouseExited

    private void X1Y4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y4MouseExited
        // TODO add your handling code here:
        X1Y4.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X1Y4MouseExited

    private void X2Y1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y1MouseExited
        // TODO add your handling code here:
        X2Y1.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X2Y1MouseExited

    private void X1Y5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y5MouseExited
        // TODO add your handling code here:
        X1Y5.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X1Y5MouseExited

    private void X1Y6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y6MouseExited
        // TODO add your handling code here:
        X1Y6.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X1Y6MouseExited

    private void X1Y7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y7MouseExited
        // TODO add your handling code here:
        X1Y7.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X1Y7MouseExited

    private void X2Y7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y7MouseExited
        // TODO add your handling code here:
        X2Y7.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X2Y7MouseExited

    private void X2Y6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y6MouseExited
        // TODO add your handling code here:
        X2Y6.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X2Y6MouseExited

    private void X2Y5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y5MouseExited
        // TODO add your handling code here:
        X2Y5.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X2Y5MouseExited

    private void X2Y4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y4MouseExited
        // TODO add your handling code here:
        X2Y4.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X2Y4MouseExited

    private void X2Y3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y3MouseExited
        // TODO add your handling code here:
        X2Y3.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X2Y3MouseExited

    private void X2Y2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y2MouseExited
        // TODO add your handling code here:
        X2Y2.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X2Y2MouseExited

    private void X3Y1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y1MouseExited
        // TODO add your handling code here:
        X3Y1.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X3Y1MouseExited

    private void X3Y2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y2MouseExited
        // TODO add your handling code here:
        X3Y2.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X3Y2MouseExited

    private void X3Y3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y3MouseExited
        // TODO add your handling code here:
        X3Y3.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X3Y3MouseExited

    private void X3Y4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y4MouseExited
        // TODO add your handling code here:
        X3Y4.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X3Y4MouseExited

    private void X3Y5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y5MouseExited
        // TODO add your handling code here:
        X3Y5.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X3Y5MouseExited

    private void X3Y6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y6MouseExited
        // TODO add your handling code here:
        X3Y6.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X3Y6MouseExited

    private void X3Y7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y7MouseExited
        // TODO add your handling code here:
        X3Y7.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X3Y7MouseExited

    private void X4Y7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y7MouseExited
        // TODO add your handling code here:
        X4Y7.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X4Y7MouseExited

    private void X4Y6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y6MouseExited
        // TODO add your handling code here:
        X4Y6.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X4Y6MouseExited

    private void X4Y5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y5MouseExited
        // TODO add your handling code here:
        X4Y5.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X4Y5MouseExited

    private void X4Y4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y4MouseExited
        // TODO add your handling code here:
        X4Y4.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X4Y4MouseExited

    private void X4Y3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y3MouseExited
        // TODO add your handling code here:
        X4Y3.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X4Y3MouseExited

    private void X4Y2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y2MouseExited
        // TODO add your handling code here:
        X4Y2.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X4Y2MouseExited

    private void X4Y1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y1MouseExited
        // TODO add your handling code here:
        X4Y1.setBorder(null);
        jLabel13.setText("");
    }//GEN-LAST:event_X4Y1MouseExited
////////////////////////////////////////////////////////////////////
    private void X1Y1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y1MouseClicked
        // TODO add your handling code here:
        x = "X1Y1";
        x1.add(x);
        //X1Y1.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 40, 20, 40, new java.awt.Color(255, 0, 51)));
        X1Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));// NOI18N

    }//GEN-LAST:event_X1Y1MouseClicked

    private void yesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesMouseClicked
        //Connection con = null;
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/oopproject", "root", "");
            Statement stmt = conn.createStatement();
            String str = jLabel1.getText();
            String str2 = "0";
            boolean check = str.equals(str2);
            if (check) {
                for (int i = 0; i < x1.size(); i++) {
                    stmt.executeUpdate("UPDATE seat SET " + y + "='1' WHERE seat='" + x1.get(i) + "'");
                    JOptionPane.showMessageDialog(this, "Seat Reaserved");
                }

            } else {
                JOptionPane.showMessageDialog(this, "First SignUp");
            }

        } catch (Exception e) {
            System.out.println("Improper connection" + e);
        }

//        try {
//
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection conn = DriverManager.getConnection(
//                    "jdbc:mysql://localhost:3306/oopproject", "root", "");
//            Statement stmt = conn.createStatement();
//            for (int i = 0; i < x1.size(); i++) {
//                stmt.executeUpdate("UPDATE seat SET " + y + "='1' WHERE seat='" + x1.get(i) + "'");
//            }
//            //UPDATE `bus` SET `AH01`='0' WHERE seat='X1Y1'
//            conn.close();
//            //rs.close();
//            stmt.close();
//        } catch (Exception e) {
//            System.out.println(e);
//        }

    }//GEN-LAST:event_yesMouseClicked

    private void X1Y2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y2MouseClicked
        // TODO add your handling code here:
        x = "X1Y2";
        x1.add(x);
        X1Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X1Y2MouseClicked

    private void X1Y3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y3MouseClicked
        // TODO add your handling code here:
        x = "X1Y3";
        x1.add(x);
        X1Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X1Y3MouseClicked

    private void X1Y4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y4MouseClicked
        // TODO add your handling code here:
        x = "X1Y4";
        x1.add(x);
        X1Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X1Y4MouseClicked

    private void X1Y5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y5MouseClicked
        // TODO add your handling code here:
        x = "XIY5";
        x1.add(x);
        X1Y5.setIcon(new javax.swing.ImageIcon("C:\\Users\\SUHANEE PATEL\\Pictures\\Screenshots\\red.JPG"));
    }//GEN-LAST:event_X1Y5MouseClicked

    private void X1Y6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y6MouseClicked
        // TODO add your handling code here:
        x = "X1Y6";
        x1.add(x);
        X1Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X1Y6MouseClicked

    private void X1Y7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1Y7MouseClicked
        // TODO add your handling code here:
        x = "X1Y7";
        x1.add(x);
        X1Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X1Y7MouseClicked

    private void X2Y1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y1MouseClicked
        // TODO add your handling code here:
        x = "X2Y1";
        x1.add(x);
        X2Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X2Y1MouseClicked

    private void X2Y2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y2MouseClicked
        // TODO add your handling code here:
        x = "X2Y2";
        x1.add(x);
        X2Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X2Y2MouseClicked

    private void X2Y3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y3MouseClicked
        // TODO add your handling code here:
        x = "X2Y3";
        x1.add(x);
        X2Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X2Y3MouseClicked

    private void X2Y4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y4MouseClicked
        // TODO add your handling code here:
        x = "X2Y4";
        x1.add(x);
        X2Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X2Y4MouseClicked

    private void X2Y5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y5MouseClicked
        // TODO add your handling code here:
        x = "X2Y5";
        x1.add(x);
        X2Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X2Y5MouseClicked

    private void X2Y6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y6MouseClicked
        // TODO add your handling code here:
        x = "X2Y6";
        x1.add(x);
        X2Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X2Y6MouseClicked

    private void X2Y7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2Y7MouseClicked
        // TODO add your handling code here:
        x = "X2Y7";
        x1.add(x);
        X2Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X2Y7MouseClicked

    private void X3Y1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y1MouseClicked
        // TODO add your handling code here:
        x = "X3Y1";
        x1.add(x);
        X3Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X3Y1MouseClicked

    private void X3Y2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y2MouseClicked
        // TODO add your handling code here:
        x = "X3Y2";
        x1.add(x);
        X3Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X3Y2MouseClicked

    private void X3Y3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y3MouseClicked
        // TODO add your handling code here:
        x = "X3Y3";
        x1.add(x);
        X3Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X3Y3MouseClicked

    private void X3Y4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y4MouseClicked
        // TODO add your handling code here:
        x = "X3Y4";
        x1.add(x);
        X3Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X3Y4MouseClicked

    private void X3Y5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y5MouseClicked
        // TODO add your handling code here:
        x = "X3Y5";
        x1.add(x);
        X3Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X3Y5MouseClicked

    private void X3Y6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y6MouseClicked
        // TODO add your handling code here:
        x = "X3Y6";
        x1.add(x);
        X3Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X3Y6MouseClicked

    private void X3Y7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3Y7MouseClicked
        // TODO add your handling code here:
        x = "X3Y7";
        x1.add(x);
        X3Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X3Y7MouseClicked

    private void X4Y1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y1MouseClicked
        // TODO add your handling code here:
        x = "X4Y1";
        x1.add(x);
        X4Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X4Y1MouseClicked

    private void X4Y2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y2MouseClicked
        // TODO add your handling code here:
        x = "X4Y2";
        x1.add(x);
        X4Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X4Y2MouseClicked

    private void X4Y3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y3MouseClicked
        // TODO add your handling code here:
        x = "X4Y3";
        x1.add(x);
        X4Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X4Y3MouseClicked

    private void X4Y4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y4MouseClicked
        // TODO add your handling code here:
        x = "X4Y4";
        x1.add(x);
        X4Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));

    }//GEN-LAST:event_X4Y4MouseClicked

    private void X4Y5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y5MouseClicked
        // TODO add your handling code here:
        x = "X4Y5";
        x1.add(x);
        X4Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X4Y5MouseClicked

    private void X4Y6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y6MouseClicked
        // TODO add your handling code here:
        x = "X4Y6";
        x1.add(x);
        X4Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X4Y6MouseClicked

    private void X4Y7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X4Y7MouseClicked
        // TODO add your handling code here:
        x = "X4Y7";
        x1.add(x);
        X4Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book.jpg")));
    }//GEN-LAST:event_X4Y7MouseClicked

    private void noMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMouseClicked
        // TODO add your handling code here:

        //this.dispose();
        new busSeat().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_noMouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/oopproject", "root", "");
            Statement stmt = conn.createStatement();
            String str = jLabel1.getText();
            String str2 = "0";
            boolean check = str.equals(str2);
            if (check) {

                TicketConfirm t = new TicketConfirm();
                t.setVisible(true);
                this.setVisible(false);
                this.dispose();
                
            } else {
                JOptionPane.showMessageDialog(this, "First SignUp");
            }

        } catch (Exception e) {
            System.out.println("Improper connection" + e);
        }


    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        loginHome x = new loginHome();
        x.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        modes x = new modes();
        x.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(busSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(busSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(busSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(busSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new busSeat().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel X1Y1;
    private javax.swing.JLabel X1Y2;
    private javax.swing.JLabel X1Y3;
    private javax.swing.JLabel X1Y4;
    private javax.swing.JLabel X1Y5;
    private javax.swing.JLabel X1Y6;
    private javax.swing.JLabel X1Y7;
    private javax.swing.JLabel X2Y1;
    private javax.swing.JLabel X2Y2;
    private javax.swing.JLabel X2Y3;
    private javax.swing.JLabel X2Y4;
    private javax.swing.JLabel X2Y5;
    private javax.swing.JLabel X2Y6;
    private javax.swing.JLabel X2Y7;
    private javax.swing.JLabel X3Y1;
    private javax.swing.JLabel X3Y2;
    private javax.swing.JLabel X3Y3;
    private javax.swing.JLabel X3Y4;
    private javax.swing.JLabel X3Y5;
    private javax.swing.JLabel X3Y6;
    private javax.swing.JLabel X3Y7;
    private javax.swing.JLabel X4Y1;
    private javax.swing.JLabel X4Y2;
    private javax.swing.JLabel X4Y3;
    private javax.swing.JLabel X4Y4;
    private javax.swing.JLabel X4Y5;
    private javax.swing.JLabel X4Y6;
    private javax.swing.JLabel X4Y7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel no;
    private javax.swing.JLabel yes;
    // End of variables declaration//GEN-END:variables

}
