package city_commute;



import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author SUHANEE PATEL
 */
public class cabConfirm extends javax.swing.JFrame {
   
    
    /**
     * Creates new form cabConfirm
     */
    public cabConfirm() {
        initComponents();
         this.setSize(1020, 750);
        Driver_f d=new Driver_f();
        jLabel16.setText(d.cabno());
        jLabel17.setText(d.driver());
        jLabel18.setText(d.driverno());
        
        Connection con = null;
        try {

            Class.forName("com.mysql.jdbc.Driver");

            String dbURL = "jdbc:mysql://localhost:3306/oopproject";

            con = DriverManager.getConnection(dbURL, "root", "");

            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from profile2 ;");
            while (rs.next()) {
                jLabel13.setText(rs.getString("pickup"));
                jLabel14.setText(rs.getString("drop_l"));
                jLabel19.setText(rs.getString("cost"));
                jLabel12.setText(rs.getString("cab_td"));
                jLabel15.setText(rs.getString("cab_type"));
                jLabel1.setText(rs.getString("name"));

            }
            stmt.close();
            con.close();
        } catch (Exception e) {
            System.out.println("Exception caught --> " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1010, 730));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("user name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(420, 60, 250, 60);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 204));
        jLabel2.setText("cab no");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 440, 64, 28);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 204));
        jLabel3.setText("booking date and time:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 140, 219, 28);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 204));
        jLabel4.setText("driver name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 530, 115, 28);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 204));
        jLabel5.setText("driver contact");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 630, 140, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 204));
        jLabel6.setText("total fare");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(650, 330, 87, 28);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 204));
        jLabel7.setText("from:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 200, 52, 28);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 204));
        jLabel8.setText("to:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(630, 200, 25, 28);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 204));
        jLabel9.setText("enter offercode");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(620, 430, 150, 28);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 204));
        jLabel10.setText("final fare");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(650, 570, 87, 28);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 204));
        jLabel11.setText("cab details");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 340, 102, 28);

        jLabel12.setFont(new java.awt.Font("Segoe Script", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("-");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(640, 140, 320, 41);

        jLabel13.setFont(new java.awt.Font("Segoe Script", 1, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("-");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(250, 190, 217, 52);

        jLabel14.setFont(new java.awt.Font("Segoe Script", 1, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("-");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(690, 190, 212, 52);

        jLabel15.setFont(new java.awt.Font("Segoe Script", 1, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("-");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(220, 330, 210, 58);

        jLabel16.setFont(new java.awt.Font("Segoe Script", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("-");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(220, 420, 340, 62);

        jLabel17.setFont(new java.awt.Font("Segoe Script", 1, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("-");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(220, 520, 217, 58);

        jLabel18.setFont(new java.awt.Font("Segoe Script", 1, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("-");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(220, 610, 260, 65);

        jLabel19.setFont(new java.awt.Font("Segoe Script", 1, 22)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("-");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(780, 310, 150, 60);

        jLabel21.setFont(new java.awt.Font("Segoe Script", 1, 22)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("-");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(810, 550, 170, 60);

        jTextField1.setFont(new java.awt.Font("DialogInput", 1, 20)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(800, 410, 180, 50);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jLabel20.setText("complete");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(740, 630, 120, 40);

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jLabel22.setText("apply");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel22);
        jLabel22.setBounds(850, 490, 110, 40);
        getContentPane().add(jLabel24);
        jLabel24.setBounds(0, 0, 0, 0);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/suhu10.png"))); // NOI18N
        jLabel23.setText("jLabel23");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel23);
        jLabel23.setBounds(940, 10, 50, 40);

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jLabel26.setText("see offer");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel26);
        jLabel26.setBounds(660, 490, 110, 40);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/capture2.JPG"))); // NOI18N
        getContentPane().add(jLabel25);
        jLabel25.setBounds(0, 0, 1000, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        String code= jTextField1.getText();
        System.out.println(code);
        if(code.equals("CODE100")||code.equals("LUCKY")||code.equals("FREERIDE")){
            String temp1=jLabel19.getText();
            System.out.println(temp1);
            int temp2=Integer.parseInt(temp1)-100;
            String temp=Integer.toString(temp2);
            jLabel21.setText(temp);
        }else if(code.equals("FLAT50")){
             String temp1=jLabel19.getText();
            int temp2=Integer.parseInt(temp1)-50;
            String temp=Integer.toString(temp2);
            jLabel21.setText(temp);
        }else if(code.equals("GET20")){
             String temp1=jLabel19.getText();
            int temp2=Integer.parseInt(temp1)-20;
            String temp=Integer.toString(temp2);
            jLabel21.setText(temp);
        }else if(code.equals("")){
             jLabel21.setText(jLabel19.getText());
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid Offer Code");
        }
        
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        loginHome x = new loginHome();
        x.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
        Offer o=new Offer();
        o.setVisible(true);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_jLabel26MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cabConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cabConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cabConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cabConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cabConfirm().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
