package city_commute;



import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author SUHANEE PATEL
 */
public class signUp extends javax.swing.JFrame {

    /**
     * Creates new form signUp
     */
    public signUp() {
        initComponents();
         this.setSize(1020, 750);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 730));
        setPreferredSize(new java.awt.Dimension(1000, 720));

        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("SIGN-UP");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(610, 30, 190, 47);

        jLabel2.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel2.setText("user name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(460, 111, 160, 40);

        jLabel3.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel3.setText("user ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(460, 190, 91, 40);

        jLabel4.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel4.setText("e-mail");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(460, 269, 90, 40);

        jLabel5.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel5.setText("password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(460, 439, 117, 40);

        jLabel6.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel6.setText("confirm password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(460, 525, 229, 40);

        jLabel7.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel7.setText("contact number");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(460, 350, 203, 40);

        jTextField1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(754, 111, 231, 60);

        jTextField2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(754, 190, 231, 60);

        jTextField3.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(754, 269, 231, 60);

        jTextField4.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(754, 352, 231, 60);

        jPasswordField1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(754, 439, 231, 60);

        jPasswordField2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(750, 520, 230, 60);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("GET STARTED");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(600, 620, 250, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/suhu12.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(930, 0, 45, 45);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/login.gif"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(-130, 60, 680, 560);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Capture3.JPG"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 1000, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String dbURL = "jdbc:mysql://localhost:3306/oopproject";
            con = DriverManager.getConnection(dbURL, "root", "");
            Statement stmt = con.createStatement();
            String uname = jTextField1.getText();
            String ID = jTextField2.getText();
            String pass = jPasswordField1.getText();
            String con_pass = jPasswordField2.getText();
            int x = Integer.parseInt(ID);
            String email = jTextField3.getText();
            String no = jTextField4.getText();

            if (pass == null ? con_pass == null : pass.equals(con_pass)) {

                String insertString = "INSERT INTO user VALUES ('" + uname + "', '" + x + "', '" + pass + "', '" + email + "', '" + no + "')";
                System.out.println(insertString);

                int i = stmt.executeUpdate(insertString);

                System.out.println("Return value from insert query = " + i);
                if (i == 1) {
                    System.out.println("Signed up successfully.");
                    String insertString1 = "INSERT INTO profile2 (`name`,`pickup`, `drop_l`, `distance`, `cost`, `time`, `bus_hr`, `bus_min`,`cab_td`, `cab_type`) VALUES ('" + jTextField1.getText() + "','"+0+"','"+0+"','"+0+"','"+0+"','"+0+"','"+0+"','"+0+"',NULL,'"+0+"')";
                    int j = stmt.executeUpdate(insertString1);
                    loginHome y = new loginHome();
                    y.setVisible(true);
                    this.setVisible(false);

                } else {
                    System.out.println("Sorry! Unable to sign up.");
                }

            } else {
                jLabel6.setForeground(new java.awt.Color(255, 51, 51));
                //jLabel6.setText("does not match");
               JOptionPane.showMessageDialog(this, "Password does not match");
            }

            stmt.close();
            con.close();
        } catch (Exception e) {
            System.out.println("Exception caught --> " + e);
            jLabel3.setForeground(new java.awt.Color(255, 51, 51));
            //jLabel3.setText("already exists");
            JOptionPane.showMessageDialog(this, "Either the info is incomplete or ID is duplicate");
        }


    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        homeScreen y = new homeScreen();
        y.setVisible(true);
        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
